---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-proxy.fullname" . }}-page-templates
  labels:
{{ include "auth-proxy.labels" . | indent 4 }}
data:
  forbidden-page: |
{{ .Values.proxyOptions.userFriendlyPages.forbiddenPageTemplate | default ( include "defaultForbiddenPage" . ) | indent 4 }}
  login-page: |
{{ .Values.proxyOptions.userFriendlyPages.loginPageTemplate | default ( include "defaultLoginPage" . ) | indent 4 }}
...
